name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main

env:
  APP_NAME: grex-springboot-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Set up JDK 17 (or other versions you are using)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Build the project and package
      - name: Build with Maven
        run: mvn clean package


      # Publish to GitHub Packages
      - name: Publish WAR to GitHub Packages
        run: |
          mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_CICD_TOKEN }}

