name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Set up JDK 17 (or other versions you are using)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Build the Spring Boot application with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run unit tests
      - name: Run Tests
        run: mvn test
